# 6.5. 汇聚层
降低卷积层对位置的敏感性，同时降低对空间降采样表示的敏感性
## 6.5.1. 最大汇聚层和平均汇聚层
池运算是确定性的，我们通常计算汇聚窗口中所有元素的最大值或平均值(池化)<br>
实现汇聚层的前向传播

In [11]:
import torch
def pool2d(X, pool_size, mode = 'max'):
    h, w = pool_size
    m, n = X.shape
    Y = torch.zeros((m - h + 1, n - w + 1))
    for i in range(m - h + 1):
        for j in range(n - w + 1):
            if mode == 'max':
                Y[i, j] = X[i: i + h, j: j + w].max()
                continue
            if mode == 'avg':
                Y[i, j] = X[i: i + h, j: j + w].mean()
                continue
    return Y

In [12]:
X = torch.tensor([[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]])
pool2d(X, (2, 2))

tensor([[4., 5.],
        [7., 8.]])

## 6.5.2. 填充和步幅
用深度学习框架中内置的二维最大汇聚层，来演示汇聚层中填充和步幅的使用<br>
默认情况下，深度学习框架中的步幅与汇聚窗口的大小相同。

In [13]:
X = torch.arange(16, dtype = torch.float32).reshape((1, 1, 4, 4))
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])

In [14]:
pool2d = torch.nn.MaxPool2d(3)
pool2d(X)

tensor([[[[10.]]]])

In [15]:
pool2d = torch.nn.MaxPool2d(3, padding = 1, stride = 2)
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

## 6.5.3. 多个通道
汇聚层在每个输入通道上单独运算，而不是像卷积层一样在通道上对输入进行汇总。<br> 
这意味着汇聚层的输出通道数与输入通道数相同。

In [16]:
X = torch.cat((X, X + 1), 1)
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]],

         [[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]]]])

In [17]:
pool2d = torch.nn.MaxPool2d(3, padding = 1, stride = 2)
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]],

         [[ 6.,  8.],
          [14., 16.]]]])