# 5.5. 读写文件
用于保存训练的模型
## 5.5.1. 加载和保存张量
直接调用load和save函数分别读写。两个函数都要求我们提供一个名称(路径名)。

In [7]:
import torch
from torch.nn import functional as F

x = torch.arange(4)
torch.save(x, '../data/x-file')

In [8]:
x2 = torch.load('../data/x-file')
x2

tensor([0, 1, 2, 3])

In [9]:
y = torch.zeros(4)
torch.save([x, y], '../data/x-files')
x2, y2 = torch.load('../data/x-files')
x2, y2

(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))

In [10]:
mydict = { 'x': x, 'y' : y }
torch.save(mydict, '../data/mydict')
mydict2 = torch.load('../data/mydict')
mydict2

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}

## 5.5.2. 加载和保存模型参数
深度学习框架提供了内置函数来保存和加载整个网络。这将保存模型的参数而不是保存整个模型。
恢复模型时，需要用代码生成架构， 然后从磁盘加载参数。

In [11]:
class MLP(torch.nn.Module):
    def __init__(self) -> None:
        super().__init__()
        self.hidden = torch.nn.Linear(20, 256)
        self.output = torch.nn.Linear(256, 10)
    def forward(self, x):
        return self.output(F.relu(self.hidden(x)))
net = MLP()
x = torch.randn(size=(2,20))
Y = net(x)

In [12]:
# 存储
torch.save(net.state_dict(), '../data/mlp.params')

In [13]:
# 恢复
clone = MLP() # 需要重新构造
clone.load_state_dict(torch.load('../data/mlp.params'))
clone.eval()

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)

In [14]:
Y_clone = clone(x)
Y_clone == Y

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])